CREATE TABLE USERS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(25) NOT NULL,
    PASSWORD VARBINARY(250),
    TYPE INT(1) NOT NULL DEFAULT 1, -- 1 = Speaker, 2 = admin
    PRIMARY KEY(ID)
);

CREATE TABLE USERS_DATA_APPROVAL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    APPROVAL_DATE DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE PHRASES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    LANGUAGE VARCHAR(2) NOT NULL,
    PHRASE TEXT NOT NULL,
    STATE INT(1) NOT NULL DEFAULT '0',
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);